##-*- makefile -*-############################################################
#  Created By    : Detlef Groth
#  Created       : Wed Jul 24 20:31:45 2024
#  Last Modified : <240724.2039>
#
#  Description	 : Makefile for compiling pexban project files
#
#  Notes         : files for homework solutions week1-week4
#
##############################################################################
#
#  Copyright (c) 2024 Detlef Groth.
# 
#  License: MIT
#
##############################################################################


default:
	g++ pexban-01.cpp -o pexban-01
	g++ pexban-02.cpp -o pexban-02
	g++ pex.cpp pexban-03.cpp -o pexban-03
	g++ pex.cpp pexban-04.cpp -o pexban-04
